### ISSUE TITLE
Desktop.browse is incompatible with OpenJDK 8 in KDE

### ISSUE THREAD

**Issue by Nutomic** [stoyicker/android-check-2#42]
The original android-check plugin works fine. Full log:
```
$ gradle check
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
:app:androidCheckstyle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:androidCheckstyle'.
> The BROWSE action is not supported on the current platform!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.723 secs
```

OS: Kubuntu 16.10
Gradle version: 3.3
OpenJDK version: 1.8.0_121

**Comment by stoyicker** [comment]
cool, thanks, will take care of that

**Comment by stoyicker** [comment]
In the meantime please see https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1574879

**Comment by stoyicker** [comment]
So I have chosen not to make a pure "fix" for this, given the fact that the alternatives to `Desktop.browse()` from the jvm seem rather dependent on the platform, ironically. If demand to support systems where `java.awt.Desktop` grows beyond marginal, I'll consider introducing an alternate fallback.
In the mean time, the commit I've referenced this issue from introduces a change that will allow the plugin to work if `java.awt.Desktop` is not supported on your system, but the report won't be opened automatically in cases where, should the class be supported, it would.

**Comment by Nutomic** [comment]
That's perfect, thanks!
